version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: echo "Building..."
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "Testing..."
  security_scan:
    docker:
      - image: security-tool:latest
    steps:
      - run: echo "Running security scans..."
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - security_scan